spring:
  datasource:
    username: cjm
    password: 9009
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    view-names: thymeleaf/*
    suffix: .html
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
