spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notepad
    username: cjm
    password: 9009
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    view-names: thymeleaf/*
    suffix: .html
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
