spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    username: cjm
    password: 9009
    url: jdbc:mysql://localhost:3306/memo
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/